"""Installer for openclaw inside an ailab container."""

import json

from .catalog_app import CatalogAppInstaller
from .. import appstore
from ..container import get_container_user, pull_file

# WebSocket path served by the openclaw gateway (used to construct tunnel
# URLs). Not part of the nimbus-app-store catalog schema — it's a protocol
# detail of openclaw's gateway, not an install/onboard step.
OPENCLAW_WS_PATH = "/__openclaw__/ws"

# openclaw's own dashboard/gateway port. The catalog's `ports` list for an
# app isn't ordered by role, so code that specifically needs *this* port
# (not just "some forwarded port") should prefer it when present rather than
# assuming ports[0] — a reordered or multi-port catalog entry would
# otherwise silently point the token-authenticated dashboard link at the
# wrong port.
OPENCLAW_DASHBOARD_PORT = 18789


def openclaw_dashboard_port(ports: list[int]) -> int | None:
    """Pick the dashboard port out of an openclaw catalog entry's ports."""
    if not ports:
        return None
    return OPENCLAW_DASHBOARD_PORT if OPENCLAW_DASHBOARD_PORT in ports else ports[0]


class OpenclawInstaller(CatalogAppInstaller):
    app_id = "openclaw"
    name = "openclaw"
    description = "AI coding agent with local-first LLM support (lemonade/ollama)"
    onboard_cmd = "openclaw onboard"

    def _read_gateway_token(self, cname: str, home: str) -> str | None:
        """Read gateway.auth.token from openclaw.json inside the container.

        Not catalog-driven — this reads openclaw's own config schema to
        support the ailab web UI's "open dashboard" link. The token itself
        is generated by the catalog's post-install script (run generically
        by CatalogAppInstaller.install/run_post_install).
        """
        try:
            raw = pull_file(cname, f"{home}/.openclaw/openclaw.json")
        except Exception:
            return None
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            return None
        return data.get("gateway", {}).get("auth", {}).get("token")

    def post_install_hints(self, cname: str) -> list[str]:
        """Print the openclaw dashboard URL including its gateway token."""
        _, _, _, home = get_container_user(cname)
        token = self._read_gateway_token(cname, home)
        if not token:
            return []
        snap = appstore.get_snap(appstore.get_catalog(), self.app_id)
        ports = appstore.get_ports(snap) if snap else []
        port = openclaw_dashboard_port(ports)
        if port is None:
            return []
        return [f"  Dashboard: http://localhost:{port}/#token={token}"]
