"""Installer for openclaw inside an ailab container."""

import json

from .catalog_app import CatalogAppInstaller
from .. import appstore
from ..container import get_container_user, pull_file

# WebSocket path served by the openclaw gateway (used to construct tunnel
# URLs). Not part of the nimbus-app-store catalog schema — it's a protocol
# detail of openclaw's gateway, not an install/onboard step.
OPENCLAW_WS_PATH = "/__openclaw__/ws"


class OpenclawInstaller(CatalogAppInstaller):
    app_id = "openclaw"
    name = "openclaw"
    description = "AI coding agent with local-first LLM support (lemonade/ollama)"
    onboard_cmd = "openclaw onboard"

    def _read_gateway_token(self, cname: str, home: str) -> str | None:
        """Read gateway.auth.token from openclaw.json inside the container.

        Not catalog-driven — this reads openclaw's own config schema to
        support the ailab web UI's "open dashboard" link. The token itself
        is generated by the catalog's post-install script (run generically
        by CatalogAppInstaller.install/run_post_install).
        """
        try:
            raw = pull_file(cname, f"{home}/.openclaw/openclaw.json")
        except Exception:
            return None
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            return None
        return data.get("gateway", {}).get("auth", {}).get("token")

    def post_install_hints(self, cname: str) -> list[str]:
        """Print the openclaw dashboard URL including its gateway token."""
        _, _, _, home = get_container_user(cname)
        token = self._read_gateway_token(cname, home)
        if not token:
            return []
        snap = appstore.get_snap(appstore.get_catalog(), self.app_id)
        ports = appstore.get_ports(snap) if snap else []
        if not ports:
            return []
        return [f"  Dashboard: http://localhost:{ports[0]}/#token={token}"]
